name: qt_learning
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.10.14
  - certifi=2021.5.30
  - dbus=1.13.18
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - jpeg=9b
  - ld_impl_linux-64=2.36.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - ncurses=6.2
  - nuitka=0.6.16.2
  - openssl=1.1.1k
  - pcre=8.44
  - pip=21.1.3
  - pyqt=5.9.2
  - python=3.9.6
  - qt=5.9.7
  - readline=8.1
  - setuptools=52.0.0
  - sip=4.19.13
  - sqlite=3.36.0
  - tk=8.6.10
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
